ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
ap_scan=1
fast_reauth=1
country=US

network={
        ssid=myrouter
        psk=forgotten
        id_str="0"
        priority=96
        scan_ssid=1
}
